### ISSUE TITLE
USER STORY: Register Account

### ISSUE THREAD

**Issue by 0davidog** [0davidog/VideoDrome#1]
# As a new user, I want to be able to register an account so that I can securely store my details for an easier checkout process.

## Acceptance Criteria

- AC1: User can access a form to register an account.
- AC2: User can create an account using their email and choose a password.
- AC3: Confirmation is given on successful account creation.

## Tasks

- [x] Install django-allauth
- [x] Stylise Log-in, Log-out and Sign Up pages.
- [x] Add Navbar links for Log-in, Log-out and Sign Up pages.
- [x] Test

**Comment by 0davidog** [comment]
Link to register:
![screen_register_link1](https://github.com/0davidog/VideoDrome/assets/135815736/59df1b13-1b56-4d85-bf19-83db4f675b12)
Link to register:
![screen_register_link2](https://github.com/0davidog/VideoDrome/assets/135815736/1e948b22-0375-4a3d-b55b-59e094a3ee71)
User can access a form to register an account:
![screen_register_form1](https://github.com/0davidog/VideoDrome/assets/135815736/8ba78ecd-a6f4-459c-bc83-ebc1d70016eb)
A couple of false attempts:
![screen_register_form2](https://github.com/0davidog/VideoDrome/assets/135815736/b1d7ab67-9f20-4525-b6c7-462f0f9950b3)
![screen_register_form3](https://github.com/0davidog/VideoDrome/assets/135815736/0d951ed5-ad17-4e1b-8740-ddfc3e97f6ba)
Sent a confirmation email:
![screen_register_confirmation](https://github.com/0davidog/VideoDrome/assets/135815736/c708658d-511e-4818-b8dd-d857e4578d42)
In the inbox:
![screen_register_confirmation_email](https://github.com/0davidog/VideoDrome/assets/135815736/d361fee6-cda8-4e70-bce0-336e707ae2e5)
Following the email link:
![screen_register_confirmation2](https://github.com/0davidog/VideoDrome/assets/135815736/e8b1a609-6cda-4adf-ba37-0a0973a1a3bb)
Successfully confirmed, taken to login page:
![screen_register_confirmation3](https://github.com/0davidog/VideoDrome/assets/135815736/24dc3ff7-bea4-4e0e-93fe-5a635ca8cbe7)
Attempted login with registered information:
![screen_register_login](https://github.com/0davidog/VideoDrome/assets/135815736/82bc5c64-2f37-4afa-b918-c071586d8205)
Success!:
![screen_register_login2](https://github.com/0davidog/VideoDrome/assets/135815736/36b84bcb-04f0-4e38-a6d0-2e7a15b5f2e0)
