### ISSUE TITLE
USER STORY: Update Basket

### ISSUE THREAD

**Issue by 0davidog** [0davidog/VideoDrome#10]
# As a shopper, I want to be able to view and edit the contents of my shopping cart before proceeding to checkout so that I can be sure of my final purchase decision.

## Acceptance Criteria

- AC1: User has access to shopping basket.
- AC2: User can edit shopping basket.
- AC3: user is informed of successful edits.

## Tasks

- [x] Add Update basket view.
- [x] Add quantity inputs to basket
- [x] Add remove button to basket

**Comment by 0davidog** [comment]
AC1: User has access to shopping basket:
![screen_update_basket1](https://github.com/0davidog/VideoDrome/assets/135815736/d5a5f7de-029e-4baf-a7f2-363bc5608680)

AC2: User can edit shopping basket and AC3: is informed of successful edits:

Add quantity:
![screen_update_basket2](https://github.com/0davidog/VideoDrome/assets/135815736/31d21f02-44ae-4ebe-b332-dd0b6f25a099)
Remove via remove link:
![screen_update_basket3](https://github.com/0davidog/VideoDrome/assets/135815736/47c71c99-55ba-405d-a45d-83aa3be3e76d)
Remove by reducing quantity input to 0:
![screen_update_basket4](https://github.com/0davidog/VideoDrome/assets/135815736/2407d010-564a-4d6e-b6f4-2b1e5c88f603)
