### ISSUE TITLE
USER STORY: Product Rating

### ISSUE THREAD

**Issue by 0davidog** [0davidog/VideoDrome#12]
# As a **registered site-user,** I can **give a star rating to a product** so that **I can express my view on product quality without writing a review.**

## Acceptance Criteria

- AC1: Registered site-user has access to rating button.
- AC2: Confirmation given on success
- AC3: Site-user can freely re-use form/link to change their rating.

## Tasks

- [x] Create rating model
- [x] Create view to handle rating requests and messages.
- [x] Create url path.
- [x] Install rating links, visible if user is logged in.
- [x] Test.

**Comment by 0davidog** [comment]
When not logged in:
![screen_rating1](https://github.com/0davidog/VideoDrome/assets/135815736/d2a964a1-d284-4c41-aae4-ccc6d9d5c81d)
AC1: Registered site-user has access to rating button.
![screen_rating2](https://github.com/0davidog/VideoDrome/assets/135815736/899d5507-d031-4dcf-b985-815a73517298)
AC2: Confirmation given on success:
![screen_rating3](https://github.com/0davidog/VideoDrome/assets/135815736/5ced4693-4ce5-42be-980c-429fe0c4682c)
User Page:
![screen_rating4](https://github.com/0davidog/VideoDrome/assets/135815736/c62e3c14-e27f-407c-b16c-5b413865a4fc)
Rating List:
![screen_rating5](https://github.com/0davidog/VideoDrome/assets/135815736/652527c6-005c-417f-92af-536cd44aae5c)
