### ISSUE TITLE
Stumbling Block Checklist

### ISSUE THREAD

**Issue by 0davidog** [0davidog/VideoDrome#13]
# To be sure, to be sure

Use this checklist to ensure you haven't missed any of the common stumbling blocks for completion of the e-commerce applications specialisation. If you are unsure of the following items, please consult the assessment criteria.

**These common stumbling blocks are NOT an exhaustive list of all your project criteria. Please consult the assessment criteria guide to understand all requirements for your project.** 

## Make sure your project includes:

- [x] At least 3 original custom models with associated functionalities, markedly different from those present in the Boutique Ado walkthrough project, if they have been used as a basis for your project. 
- [x] At least one form on the front end, which provides either admin or regular users with CRUD functionality without having to access the admin panel. 
- [x] At least one UI element on the front end, which allows either admin or regular users to delete records in the database without having to access the admin panel.
- [x] Evidence of agile methodologies followed during the development of your project in the GitHub repository. 
- [x] A robots.txt file. 
- [x] A sitemap.xml file. 
- [x] Descriptive meta tags in the HTML. 
- [x] At least one link to an external resource, which makes use of a rel attribute. 
- [x] A custom 404 error page.
- [x] Evidence of either a real Facebook business page, or mock-up of one, for the purposes of digital marketing. 
- [x] Evidence of a newsletter signup form for the purposes of digital marketing. 
- [x] A description of the e-commerce business model including marketing strategies in the README file. 
- [x] DEBUG mode set to False. 
- [x] Working functionality for users to register and log in and out of the application without issues. 
- [x] Working E-commerce functionality for users to make purchases within the application. 
- [x] Detailed testing write-ups, beyond results of validation tools. 
- [x] GitHub project board set to public visibility.
