### ISSUE TITLE
USER STORY: Checkout

### ISSUE THREAD

**Issue by 0davidog** [0davidog/VideoDrome#15]
# As a shopper, I want to be able to securely check out and provide shipping and payment information so that I may purchase items with ease and confidence.

## Acceptance Criteria

- AC1: User, with items in basket, can proceed to checkout.
- AC2: User, at checkout, can provide their billing and shipping information.
- AC3: User is informed of successful or unsuccessful purchase attempt.
- AC4: User is taken to success page on completion of purchase.

## Tasks

- [x] Create checkout view, template, url.
- [x] Install Stripe
- [x] Install Stripe card element
- [x] Install Stripe webhook listener.
- [x] Test

**Comment by 0davidog** [comment]
AC1: User, with items in basket, can proceed to checkout.

Checkout button in basket:
![checkout1](https://github.com/0davidog/VideoDrome/assets/135815736/8714cd75-b402-4be8-997e-01292429d115)

Checkout Page:
![checkout2](https://github.com/0davidog/VideoDrome/assets/135815736/fbdb2a42-43b2-4242-bc0c-bbd06f22ebb6)

AC2: User, at checkout, can provide their billing and shipping information.

Billing and shipping form:
![checkout3](https://github.com/0davidog/VideoDrome/assets/135815736/d0cda09b-39fd-481c-9344-22f0fa118759)

Payment form:
![checkout4](https://github.com/0davidog/VideoDrome/assets/135815736/8bd9d7fe-6f80-4ced-84d1-075e6ede9e54)

A warning model simulating terms and conditions:
![checkout5](https://github.com/0davidog/VideoDrome/assets/135815736/1ac82ca5-a4da-43e1-99af-1b648820309a)

Stripe's form validation:
![checkout6](https://github.com/0davidog/VideoDrome/assets/135815736/f7db1009-267e-4ab7-adf3-f2c08857e401)

Checkout success:
![checkout7](https://github.com/0davidog/VideoDrome/assets/135815736/0a28bee0-e2d5-4f4e-a50f-a5351f229713)

Confirmation email:
![checkout8](https://github.com/0davidog/VideoDrome/assets/135815736/f8baba29-4dd9-4b31-9e24-813a65997f3e)
