### ISSUE TITLE
USER STORY: Account Log-in

### ISSUE THREAD

**Issue by 0davidog** [0davidog/VideoDrome#2]
# As a registered user, I want to be able to log in to my account securely so that I can shop easily with my saved information.

## Acceptance Criteria

- AC1: User can access a form to log-in.
- AC2: User can then enter registered details to log-in.
- AC3: Notice is given for unsuccessful log-in attempt.
- AC4: Confirmation is given upon successful log-in.

## Tasks

- [x] Install django-allauth
- [x] Stylise log-in page.
- [x] Add navbar link to log-in page.
- [x] Add message function.
- [x] Test

**Comment by 0davidog** [comment]
Link to login:
![screen_login_link](https://github.com/0davidog/VideoDrome/assets/135815736/9f3d30bc-b989-43d7-a8c7-1b80208089b1)
Link to Login:
![screen_login_link2](https://github.com/0davidog/VideoDrome/assets/135815736/50e507db-cf96-41f0-b525-f7a0538bbf44)
AC1: User can access a form to log-in.
![screen_login_form](https://github.com/0davidog/VideoDrome/assets/135815736/88c535a5-26b4-44bd-aa5d-06b16fba9c22)
AC2: User can then enter registered details to log-in.
![screen_login_form2](https://github.com/0davidog/VideoDrome/assets/135815736/f17a9955-0526-4148-8d27-0f757fcf0e0b)
AC3: Notice is given for unsuccessful log-in attempt.
![screen_login_form3](https://github.com/0davidog/VideoDrome/assets/135815736/243c74e8-0995-43da-9ee0-284965efb015)
![screen_login_form4](https://github.com/0davidog/VideoDrome/assets/135815736/08b222f5-a23b-4c0f-9417-bb69d3db56ce)
AC4: Confirmation is given upon successful log-in.
![screen_login_form_success](https://github.com/0davidog/VideoDrome/assets/135815736/c2c44bcc-45bb-4a8f-b48e-d6f1c1c60b12)
