### ISSUE TITLE
USER STORY: Order History

### ISSUE THREAD

**Issue by 0davidog** [0davidog/VideoDrome#25]
# As a shopper, I want to be able to view my order history so that I access the information for my records or a query.

## Acceptance Criteria

- AC1: A logged in user can access a list of previous orders.
- AC2: The list links to detailed order pages.

## Tasks

- [x] Add order list to customer info page view
- [x] Create order page view
- [x] Create order page template
- [x] Add urls
- [x] Link up order list and detail pages.

**Comment by 0davidog** [comment]
Orders list on user page:
![orders1](https://github.com/0davidog/VideoDrome/assets/135815736/436c0306-3769-457f-a3dc-b6488236cee6)

Hover to see full number:
![orders2](https://github.com/0davidog/VideoDrome/assets/135815736/7bd2ab8b-7976-47f2-8a2f-09b9c6b05821)

Follow link for order detail:
![orders3](https://github.com/0davidog/VideoDrome/assets/135815736/57057c0b-67a9-4b0b-99ae-29d4a19e2a32)
