### ISSUE TITLE
USER STORY: Add Product

### ISSUE THREAD

**Issue by 0davidog** [0davidog/VideoDrome#28]
# As a site-admin, I want to be able to add a product without the admin panel so that my work flow can stay oriented to the site.

## Acceptance Criteria

- AC1: Logged in, admin has link to add product.
- AC2: Admin is taken to add product form.
- AC3: Message given for success.
- AC4: Message given for failure.
- AC5: Once submitted, product can be seen in database.

## Tasks

- [x] Add form for product model.
- [x] Add view for form.
- [x] Add template.
- [x] Add to urls.
- [x] Test Form.

**Comment by 0davidog** [comment]
AC1: Logged in, admin has link to add product.
![video_add1](https://github.com/0davidog/VideoDrome/assets/135815736/c3545a11-ad5f-47f5-aa7f-1d4d4d844c3b)

AC2: Admin is taken to add product form.
![video_add2](https://github.com/0davidog/VideoDrome/assets/135815736/12e343ab-103b-4750-a052-df73eedf51a6)
![video_add3](https://github.com/0davidog/VideoDrome/assets/135815736/e0bcb189-4a64-4dba-acb3-8ddaefb93ff6)

AC3: Message given for success.
![video_add4](https://github.com/0davidog/VideoDrome/assets/135815736/e7288dc2-d979-48d3-b082-af9c28a5e639)

AC4: Message given for failure.
![video_add5](https://github.com/0davidog/VideoDrome/assets/135815736/ecce50f5-cf3d-418f-bd95-615ad9cb0e4f)

AC5: Once submitted, product can be seen in database.
![video_add6](https://github.com/0davidog/VideoDrome/assets/135815736/6882071d-4686-40f4-96ce-84adae1c061a)
![video_add7](https://github.com/0davidog/VideoDrome/assets/135815736/4b07a554-a69b-405d-839b-184999323484)
![video_add8](https://github.com/0davidog/VideoDrome/assets/135815736/828a3b87-c90d-4fe1-884f-1a786bbb7ee7)
