### ISSUE TITLE
USER STORY: Password Reset

### ISSUE THREAD

**Issue by 0davidog** [0davidog/VideoDrome#3]
# As a Site user, I want the option to reset my password in case I forget it, ensuring secure access to my account.

## Acceptance Criteria

- AC1: User can access a form for password reset.
- AC2: User can then enter details to perform a password reset.
- AC3: Confirmation is given for successful password reset.

## Tasks

- [x] install django-allauth
- [x] Add link to log-in page on navigation bar.
- [x] Style log-in page.
- [x] Check for link to password reset on log-in page.
- [x] Style password reset page.
- [x] Test

**Comment by 0davidog** [comment]
Link to Password reset on login page:
![screen_passchange_1](https://github.com/0davidog/VideoDrome/assets/135815736/cf6150c0-17a0-400b-92fd-b4d3b02419b9)
AC1: User can access a form for password reset.
![screen_passchange_2](https://github.com/0davidog/VideoDrome/assets/135815736/3cf941c4-0990-4453-9cf6-93364ca4effe)
AC2: User can then enter details to perform a password reset.
![screen_passchange_3](https://github.com/0davidog/VideoDrome/assets/135815736/9c5bdeb8-b821-498c-8a3e-8a605f5011cf)
![screen_passchange_email](https://github.com/0davidog/VideoDrome/assets/135815736/92b6ed43-c787-44bc-828f-eb9d0ca837a3)
![screen_passchange_4](https://github.com/0davidog/VideoDrome/assets/135815736/b7c26c9a-6be1-4d25-b4ce-9f2038227ae2)
AC3: Confirmation is given for successful password reset.
![screen_passchange_5](https://github.com/0davidog/VideoDrome/assets/135815736/e0887cba-de29-47ca-b09a-ea5a0840eb84)
