### ISSUE TITLE
USER STORY: Delete Product

### ISSUE THREAD

**Issue by 0davidog** [0davidog/VideoDrome#30]
# As a site-admin I want to be able to delete a product without the admin panel so that my work flow can stay oriented to the site.

## Acceptance Criteria

- AC1: Logged in, admin has link to delete product.
- AC2: Admin is shown a confirmation modal.
- AC3: Message given for success.
- AC4: Message given for failure.
- AC5: Once submitted, changes can be seen in database.

## Tasks

- [x] Add delete view
- [x] Add delete link
- [x] Add modal
- [x] Add to urls
- [x] Test

**Comment by 0davidog** [comment]
AC1: Logged in, admin has link to delete product.

![video_delete3](https://github.com/0davidog/VideoDrome/assets/135815736/d2e4cf47-58f0-4ecf-ace5-168ebe835803)

AC2: Admin is shown a confirmation modal.

![video_delete4](https://github.com/0davidog/VideoDrome/assets/135815736/4ce820fd-34e1-4857-9764-17f15d78f174)

AC3: Message given for success.

![video_delete5](https://github.com/0davidog/VideoDrome/assets/135815736/b2e3ca66-0540-4078-b7f5-7e4596f11f30)

Attempt to delete by url without correct authentication:

![video_delete1](https://github.com/0davidog/VideoDrome/assets/135815736/921a01cd-569e-4dcf-96a7-8083f533feb7)

AC4: Message given for failure:

![video_delete2](https://github.com/0davidog/VideoDrome/assets/135815736/72809a69-deb3-4bfd-b999-114260701431)
