### ISSUE TITLE
USER STORY: Navigation menu

### ISSUE THREAD

**Issue by 0davidog** [0davidog/VideoDrome#32]
# As a Site User, I want a user-friendly navigation menu that helps me explore different sections of the site easily.

## Acceptance Criteria

- AC1: User has access to navigation bar/menu.
- AC2: Navigation menu is clear to understand.
- AC3: Selecting links takes user to expected site locations.

## Tasks

- [x] Add navigation bar/menu to base.html.
- [x] Wire up links.
- [x] Test links.

**Comment by 0davidog** [comment]
Desktop Navigation:

![nav1](https://github.com/0davidog/VideoDrome/assets/135815736/788cee35-ac54-49a2-a927-0841b7a97476)

With Admin Authentication:

![nav3](https://github.com/0davidog/VideoDrome/assets/135815736/406c681d-5bab-4484-9c35-8fcbee12ae66)

Mobile Navigation (collapsable nav bar):

![nav2](https://github.com/0davidog/VideoDrome/assets/135815736/ada990ee-24b9-4b3e-9cd6-98242180cc59)

With Admin Authentication:

![nav4](https://github.com/0davidog/VideoDrome/assets/135815736/cc0b5ea1-4fe4-4c31-96f8-b2fd0b9ab7cd)

**Comment by 0davidog** [comment]
## Test Links for expected outcomes.

### Desktop

- [x] Home Link 'VideoDrome' as Heading.
- [x] 'All Videos'
- [x] 'By Format' - 'DVD'
- [x] 'By Format' - 'Blu-Ray'
- [x] 'By Format' - '4k Ultra HD'
- [x] 'By Genre' - 'Drama'
- [x] 'By Genre' - 'Thriller'
- [x] 'By Genre' - 'Horror'
- [x] 'By Genre' - 'Sci-Fi'
- [x] 'By Genre' - 'Erotic'
- [x] 'By Genre' - 'Comedy'
- [x] 'By Genre' - 'Romance'
- [x] 'Hello' - 'Login'
- [x] 'Hello - 'Register'
- [x] 'Hello' - 'User'
- [x] 'My Account' - 'Sign in'
- [x] 'My Account' - 'Register'
- [x] 'My Account' - 'Account Info'
- [x] 'My Account' - 'Sign Out'
- [x] 'Admin' - 'Admin Panel'
- [x] 'Admin' - 'Inventory List'
- [x] 'Admin' - 'Orders'
- [x] 'Admin' - 'Add Video'
- [x] 'Basket'

### Mobile

- [x] Home Link 'VideoDrome' as Heading.
- [x] 'All Videos'
- [x] 'By Format' - 'DVD'
- [x] 'By Format' - 'Blu-Ray'
- [x] 'By Format' - '4k Ultra HD'
- [x] 'By Genre' - 'Drama'
- [x] 'By Genre' - 'Thriller'
- [x] 'By Genre' - 'Horror'
- [x] 'By Genre' - 'Sci-Fi'
- [x] 'By Genre' - 'Erotic'
- [x] 'By Genre' - 'Comedy'
- [x] 'By Genre' - 'Romance'
- [x] 'Hello' - 'Login'
- [x] 'Hello - 'Register'
- [x] 'Hello' - 'User'
- [x] 'My Account' - 'Sign in'
- [x] 'My Account' - 'Register'
- [x] 'My Account' - 'Account Info'
- [x] 'My Account' - 'Sign Out'
- [x] 'Admin' - 'Admin Panel'
- [x] 'Admin' - 'Inventory List'
- [x] 'Admin' - 'Orders'
- [x] 'Admin' - 'Add Video'
- [x] 'Basket'
