### ISSUE TITLE
USER STORY: Create Review

### ISSUE THREAD

**Issue by 0davidog** [0davidog/VideoDrome#33]
# As a registered site user, I would like to leave a review on a product I have already purchased so that I might help others be informed.

## Acceptance Criteria

- AC1: Logged-in user has access to review link.
- AC2: User can then fill in review form.
- AC3: Message on success.

## Tasks

- [x] create review view
- [x] create review template
- [x] add to urls
- [x] test

**Comment by 0davidog** [comment]
Link when not authenticated:

![review01](https://github.com/0davidog/VideoDrome/assets/135815736/23fcf547-5af8-41ba-8efc-cf4366b5eb1b)

Review Link:

![review02](https://github.com/0davidog/VideoDrome/assets/135815736/46e5514d-20ec-4fbe-880e-e790ca551264)

Review Form:

![review03](https://github.com/0davidog/VideoDrome/assets/135815736/19aa31c9-84e6-4264-93b2-c8d93aeeed5e)
![review04](https://github.com/0davidog/VideoDrome/assets/135815736/a982fe21-189b-453e-bb0c-3510bd2fdad7)

Successful attempt:

![review05](https://github.com/0davidog/VideoDrome/assets/135815736/9deacd42-88e0-4d05-9171-0e5e1966b071)

Review can be seen in customer page even before admin approval:

![review06](https://github.com/0davidog/VideoDrome/assets/135815736/18af5e8a-0975-4fac-a445-dbe6f31a4632)

After admin approval:

![review07](https://github.com/0davidog/VideoDrome/assets/135815736/d518ed35-0a0a-4f31-bec0-fadb6b86ba6c)

Attempting to access the form, having written a review already, leads to edit review form:

![review08](https://github.com/0davidog/VideoDrome/assets/135815736/1705f44d-b4a7-48e9-985c-9214b6370346)

Attempting empty form:

![review09](https://github.com/0davidog/VideoDrome/assets/135815736/e6386ea1-dbfb-40e3-9fab-a4b386c43f73)
