### ISSUE TITLE
USER STORY: Product Category

### ISSUE THREAD

**Issue by 0davidog** [0davidog/VideoDrome#4]
# As a user, I want to be able to browse products by category so that I can better find the kind of products I'm interested in.

## Acceptance Criteria

- AC1: User has access to list of products.
- AC2: User has access to product category filter button or link.
- AC3: User than sees products filtered by category.

## Tasks

- [x] Create page displaying all products.
- [x] Install links to all products view with attached queries.
- [x] Create code in view to handle queries and filter products.
- [x] Test

**Comment by 0davidog** [comment]
AC1: User has access to list of products:
![screen_videos1](https://github.com/0davidog/VideoDrome/assets/135815736/03fd6fab-4987-4ebe-9c5a-cc972850e4ab)

AC2: User has access to product category filter button or link.
AC3: User than sees products filtered by category.

Filtered by format:
![screen_videos2](https://github.com/0davidog/VideoDrome/assets/135815736/1beb2263-89e4-4336-a7e2-6a39881b3908)
![screen_videos3](https://github.com/0davidog/VideoDrome/assets/135815736/48f7cd77-830a-4a55-b17c-15db485a5811)
![screen_videos4](https://github.com/0davidog/VideoDrome/assets/135815736/afb9f9f7-0cd8-4218-ae04-67b904368ff6)

Filtered by genre:
![screen_videos5](https://github.com/0davidog/VideoDrome/assets/135815736/29c37ab7-2c6f-43c5-8c32-430b4247e053)
![screen_videos6](https://github.com/0davidog/VideoDrome/assets/135815736/68a99ad3-a71a-4900-be02-428d76d722bb)
