### ISSUE TITLE
USER STORY: Product Detail

### ISSUE THREAD

**Issue by 0davidog** [0davidog/VideoDrome#6]
# As a shopper, I want to view detailed information about a product, including images, descriptions, and specifications so that I can be better informed about my purchases.

## Acceptance Criteria

- AC1: User has access to list of available products.
- AC2: User can click on a product link to access a product detail page.

## Tasks

- [x] Create product detail view
- [x] Create product detail template
- [x] Create product detail url path.

**Comment by 0davidog** [comment]
AC1: User has access to list of available products.
![screen_detail1](https://github.com/0davidog/VideoDrome/assets/135815736/7af4039d-90cf-4af3-9de8-0081b907d811)
AC2: User can click on a product link to access a product detail page.
![screen_detail2](https://github.com/0davidog/VideoDrome/assets/135815736/7ef3de44-d5bd-4b63-9650-487723a0a98a)
