### ISSUE TITLE
USER STORY: Product Wishlist

### ISSUE THREAD

**Issue by 0davidog** [0davidog/VideoDrome#8]
# As a registered site-user, I want to be able to add a product to my wishlist so that I can easily return to a product I want to purchase at a more convenient time.

## Acceptance Criteria

- AC1: Logged in site-user has access to wishlist link.
- AC2: Clearly visible from product detail page whether product is in wishlist or not.
- AC3: Wishlist can be viewed on user page.

## Tasks

- [x] Wishlist field on product model.
- [x] Create view to handle request.
- [x] Create url path.
- [x] Install add to wishlist link, visible when user logged in.
- [x] Link clearly states 'in wishlist' or 'add to wishlist'.
- [x] Display user's wishlist on user page.

**Comment by 0davidog** [comment]
When not logged in:
![screen_wishlist1](https://github.com/0davidog/VideoDrome/assets/135815736/d77051e5-b32e-4285-bd45-39126e957965)
AC1: Logged in site-user has access to wishlist link:
![screen_wishlist2](https://github.com/0davidog/VideoDrome/assets/135815736/cea449b9-6e63-4467-abfd-d9f3ee53f20e)
AC2: Clearly visible from product detail page whether product is in wishlist or not:
![screen_wishlist3](https://github.com/0davidog/VideoDrome/assets/135815736/0a2ab880-da78-47c6-806b-932700fcc8e9)
User page:
![screen_wishlist4](https://github.com/0davidog/VideoDrome/assets/135815736/1bd665b0-b802-4e12-80dd-ed884335b5a1)
AC3: Wishlist can be viewed on user page:
![screen_wishlist5](https://github.com/0davidog/VideoDrome/assets/135815736/e7a11f42-b8e1-477b-b8b0-4c6c1a74f84e)
