### ISSUE TITLE
USER STORY: Add to Basket

### ISSUE THREAD

**Issue by 0davidog** [0davidog/VideoDrome#9]
# As a shopper, I want to be able to add items to my shopping basket so that I can purchase multiple products in one transaction.

## Acceptance Criteria

- AC1: User has access to 'add to basket' button on product.
- AC2: Button adds chosen quantity of product to basket.

## Tasks

- [x] Add basket app.
- [x] Add basket context.
- [x] Add 'add to basket' button.

**Comment by 0davidog** [comment]
AC1: User has access to 'add to basket' button on product.
List view:
![screen_basket1](https://github.com/0davidog/VideoDrome/assets/135815736/3e5d49d6-fb9c-4fe3-930f-2818959599ba)
Detail View:
![screen_basket2](https://github.com/0davidog/VideoDrome/assets/135815736/ef5ad7a6-2c35-459c-ba3c-a0e0e8d1daf8)
Confirmation:
![screen_basket3](https://github.com/0davidog/VideoDrome/assets/135815736/ded85579-78c0-4afd-96c5-3e51a7455b7c)
Basket:
![screen_basket4](https://github.com/0davidog/VideoDrome/assets/135815736/305af7f4-3144-4e38-b43e-1c63091a3462)
